# Ultimate Quantum Mempool Monitor - Production Docker Compose
version: '3.8'

services:
  # Main application service
  quantum-monitor:
    build:
      context: .
      dockerfile: Dockerfile.ultimate
      target: production
    container_name: ultimate-quantum-monitor
    restart: unless-stopped
    ports:
      - "8000:8000"  # Main API
      - "8001:8001"  # Dashboard
      - "8765:8765"  # WebSocket
      - "9090:9090"  # Metrics
    environment:
      - QUANTUM_ENV=production
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=quantum_mempool
      - POSTGRES_USER=quantum_user
      - POSTGRES_PASSWORD=quantum_secure_password_2024
    volumes:
      - quantum_logs:/app/logs
      - quantum_data:/app/data
      - quantum_config:/app/config
      - ./config/unified-config.yaml:/app/config/unified-config.yaml:ro
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - quantum-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: quantum-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass quantum_redis_2024
    volumes:
      - quantum_redis_data:/data
    networks:
      - quantum-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # PostgreSQL for persistent data storage
  postgres:
    image: postgres:15-alpine
    container_name: quantum-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quantum_mempool
      - POSTGRES_USER=quantum_user
      - POSTGRES_PASSWORD=quantum_secure_password_2024
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - quantum_postgres_data:/var/lib/postgresql/data
    networks:
      - quantum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantum_user -d quantum_mempool"]
      interval: 10s
      timeout: 5s
      retries: 5

# Named volumes for data persistence
volumes:
  quantum_logs:
    driver: local
  quantum_data:
    driver: local
  quantum_config:
    driver: local
  quantum_redis_data:
    driver: local
  quantum_postgres_data:
    driver: local

# Network for service communication
networks:
  quantum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
