services:
  postgres:
    image: postgres:15
    container_name: scorpius-postgres
    environment:
      POSTGRES_DB: scorpius
      POSTGRES_USER: scorpius
      POSTGRES_PASSWORD: scorpius_secure_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scorpius-network

  redis:
    image: redis:7-alpine
    container_name: scorpius-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scorpius-network

  prometheus:
    image: prom/prometheus:latest
    container_name: scorpius-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - scorpius-network

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: scorpius-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - scorpius-network

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile.simple
    container_name: scorpius-api-gateway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://scorpius:scorpius_secure_2024@postgres:5432/scorpius
      - REDIS_URL=redis://redis:6379
      - DISABLE_DATABASE=true
    depends_on:
      - postgres
      - redis
    networks:
      - scorpius-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    container_name: scorpius-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api-gateway
    networks:
      - scorpius-network

networks:
  scorpius-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
