services:
  postgres:
    image: postgres:15
    container_name: scorpius-postgres
    environment:
      POSTGRES_DB: scorpius
      POSTGRES_USER: scorpius
      POSTGRES_PASSWORD: scorpius_secure_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scorpius-network

  redis:
    image: redis:7-alpine
    container_name: scorpius-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scorpius-network

  prometheus:
    image: prom/prometheus:latest
    container_name: scorpius-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - scorpius-network

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: scorpius-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - scorpius-network

networks:
  scorpius-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
