version: "3.9"

services:
  # API Gateway - Entry point for all requests
  api-gateway:
    build: ./api-gateway/app
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://scorpius:scorpius123@postgres:5432/scorpius_db
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
    networks:
      - scorpius-network
    restart: unless-stopped

  # Time Machine Service - Historical blockchain state replay
  time-machine-service:
    build: ./time-machine-service/app
    ports:
      - "8081:8000"
    environment:
      - REDIS_URL=redis://redis:6379/1
      - POSTGRES_URL=postgresql://scorpius:scorpius123@postgres:5432/scorpius_db
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
    networks:
      - scorpius-network
    restart: unless-stopped
    volumes:
      - time_machine_data:/app/store

  # Reporting Service - Analytics and reporting
  reporting-service:
    build: ./reporting-service/app
    ports:
      - "8082:8000"
    environment:
      - DATABASE_URL=postgresql://scorpius:scorpius123@postgres:5432/scorpius_db
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      - postgres
      - redis
    networks:
      - scorpius-network
    restart: unless-stopped
    volumes:
      - reporting_data:/app/reports

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=scorpius_db
      - POSTGRES_USER=scorpius
      - POSTGRES_PASSWORD=scorpius123
    ports:
      - "5432:5432"
    networks:
      - scorpius-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - scorpius-network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@scorpius.local
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8083:80"
    depends_on:
      - postgres
    networks:
      - scorpius-network
    restart: unless-stopped

  # Redis Commander for Redis management
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8084:8081"
    depends_on:
      - redis
    networks:
      - scorpius-network
    restart: unless-stopped

networks:
  scorpius-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  time_machine_data:
  reporting_data:
