global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "dashboard-api"
    static_configs:
      - targets: ["dashboard-api:8001"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "scorpius-microservices"
    static_configs:
      - targets: ["api-gateway:8000", "dashboard-api:8001"]
    metrics_path: "/health"
    scrape_interval: 10s
    scrape_interval: 5s
