# Enterprise Quantum Mempool Monitor Configuration

# Core Application Settings
app:
  name: "quantum-mempool-monitor"
  version: "1.0.0"
  environment: "production"
  debug: false
  log_level: "INFO"

# Detection Parameters
detection:
  threshold: 100
  time_window: 600  # 10 minutes
  confidence_threshold: 0.85
  temporal_threshold: 0.7
  statistical_threshold: 0.8
  minimum_transactions: 10

# Blockchain Network Configuration
bitcoin:
  node_url: "http://localhost:8332"
  rpc_user: "bitcoin_user"
  rpc_password: "bitcoin_password"
  websocket_url: "wss://mempool.space/api/v1/ws"
  timeout: 30

ethereum:
  provider_url: "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
  private_key: ""
  gas_limit: 500000
  timeout: 30

# Enterprise Security Configuration
enterprise:
  deployment:
    environment: "production"
    region: "multi-region"
    availability_zones: 3
    encryption_at_rest: true
    encryption_in_transit: true
    
  security:
    hsm:
      provider: "aws-cloudhsm"
      fips_compliance: "level-3"
      key_rotation_interval: "quarterly"
      connection_timeout: 30
      retry_attempts: 3
      
    rbac:
      backend: "eos-blockchain"
      enforcement_mode: "strict"
      separation_of_duties: true
      multi_factor_auth: true
      session_timeout: 3600
      
    audit:
      blockchain_audit_trail: true
      immutable_logging: true
      real_time_siem_integration: true
      retention_period: "7_years"
      encryption_enabled: true
      
  compliance:
    frameworks:
      - "SOX"
      - "GDPR" 
      - "PCI_DSS"
      - "NIST_Cybersecurity_Framework"
      - "ISO_27001"
    automated_reporting: true
    continuous_compliance_monitoring: true
    
  monitoring:
    prometheus_enabled: true
    prometheus_port: 9090
    collection_interval: 60
    retention_days: 365
    high_availability: true
    external_labels:
      env: "production"
      service: "quantum-monitor"
      
    grafana:
      high_availability: true
      ldap_integration: true
      dashboard_provisioning: true
      
    alerting:
      escalation_policies: true
      integration_platforms:
        - "pagerduty"
        - "slack"
        - "email"
        - "sms"
        
  incident_response:
    automated_playbooks: true
    crisis_communication: true
    forensics_collection: true
    business_continuity_integration: true
    
  business_continuity:
    rpo: "1_minute"  # Recovery Point Objective
    rto: "5_minutes"  # Recovery Time Objective
    backup_frequency: "continuous"
    cross_region_replication: true
    disaster_recovery_testing: "monthly"

# SIEM Integration
siem:
  splunk_enabled: true
  splunk_host: "splunk.enterprise.local"
  splunk_port: 8089
  splunk_index: "quantum_security"
  
  elastic_enabled: true
  elastic_host: "elasticsearch.enterprise.local"
  elastic_port: 9200
  elastic_index: "quantum-security"
  
  real_time_streaming: true
  event_correlation: true
  threat_intelligence_integration: true

# Database Configuration
database:
  url: "postgresql://quantum_user:quantum_pass@postgres:5432/quantum_monitor"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  encryption_at_rest: true
  backup_enabled: true
  backup_retention_days: 365

# Redis Configuration
redis:
  host: "redis.enterprise.local"
  port: 6379
  db: 0
  password: "redis_password"
  ssl_enabled: true
  cluster_mode: true

# Message Queue Configuration
message_queue:
  provider: "rabbitmq"
  host: "rabbitmq.enterprise.local"
  port: 5672
  username: "quantum_mq"
  password: "mq_password"
  ssl_enabled: true
  high_availability: true

# Emergency Response Configuration
emergency:
  timelock_contract: "0x1234567890123456789012345678901234567890"
  emergency_delay: 7200  # 2 hours
  pause_duration: 604800  # 7 days
  multi_sig_required: true
  minimum_signers: 3

# Revocation System Configuration
revocation:
  private_key_path: "/secure/keys/revocation_private_key.pem"
  public_key_path: "/secure/keys/revocation_public_key.pem"
  hsm_key_id: "revocation_key_001"
  distribution_channels:
    - "websocket"
    - "http"
    - "push_notifications"
    - "blockchain"

# Wallet Notification Configuration
notifications:
  websocket_endpoints:
    - "wss://wallet-service-1.enterprise.local/alerts"
    - "wss://wallet-service-2.enterprise.local/alerts"
  
  http_endpoints:
    - "https://api.wallet1.enterprise.local/v1/alerts"
    - "https://api.wallet2.enterprise.local/v1/notifications"
  
  push_notifications:
    firebase:
      server_key: "${FIREBASE_SERVER_KEY}"
      sender_id: "${FIREBASE_SENDER_ID}"
    
    apns:
      team_id: "${APNS_TEAM_ID}"
      key_id: "${APNS_KEY_ID}"
      private_key_path: "/secure/keys/apns_private_key.p8"

# Kubernetes Configuration
kubernetes:
  namespace: "quantum-monitor"
  service_mesh: "istio"
  ingress_controller: "nginx"
  
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "8"
      memory: "16Gi"
  
  scaling:
    min_replicas: 3
    max_replicas: 20
    target_cpu_utilization: 70
    target_memory_utilization: 80

# Observability Configuration
observability:
  tracing:
    provider: "jaeger"
    sampling_rate: 0.1
    endpoint: "http://jaeger-collector:14268/api/traces"
  
  metrics:
    provider: "prometheus"
    scrape_interval: "15s"
    evaluation_interval: "15s"
  
  logging:
    level: "INFO"
    format: "json"
    structured: true
    correlation_id_enabled: true
    
# Security Scanning Configuration
security_scanning:
  vulnerability_scanning: true
  dependency_scanning: true
  secret_scanning: true
  compliance_scanning: true
  
  scan_schedule: "daily"
  critical_threshold: 0
  high_threshold: 5
  medium_threshold: 20

# Backup and Recovery Configuration
backup:
  encryption_enabled: true
  compression_enabled: true
  retention_policy:
    daily: 30
    weekly: 12
    monthly: 12
    yearly: 7
  
  storage:
    provider: "aws-s3"
    bucket: "quantum-monitor-backups"
    region: "us-east-1"
    encryption: "AES-256"

# Integration Configuration
integrations:
  threat_intelligence:
    providers:
      - "misp"
      - "threatconnect"
      - "virustotal"
    update_frequency: "hourly"
  
  vulnerability_databases:
    - "nvd"
    - "cve"
    - "exploit-db"
  
  regulatory_feeds:
    - "nist"
    - "iso"
    - "pci"
