# Ultimate Unified Scanner Configuration
# Enterprise-grade vulnerability scanning with quantum threat detection

# Application Settings
app:
  name: "ultimate-vulnerability-scanner"
  version: "2.0.0"
  environment: "production"
  debug: false
  log_level: "INFO"

# Orchestrator Configuration
orchestrator:
  mode: "unified"
  max_concurrent_scans: 10
  scan_timeout: 3600  # 1 hour
  result_retention_days: 90
  auto_scan_enabled: true
  
  # AI-powered analysis
  ai:
    enabled: true
    model: "gpt-4-turbo"
    confidence_threshold: 0.85
    max_tokens: 4000
    temperature: 0.2
    
  # Integration settings
  integration:
    quantum_monitor_enabled: true
    mempool_monitoring_enabled: true
    real_time_alerts: true
    webhook_notifications: true

# Scanner-Specific Configurations
scanners:
  quantum:
    enabled: true
    priority: 1
    config:
      confidence_threshold: 0.8
      temporal_clustering_window: 600
      entropy_analysis_enabled: true
      ml_model_enabled: true
      detection_algorithms:
        - temporal_clustering
        - fee_uniformity
        - geometric_pattern
        - entropy_analysis
        - statistical_anomaly
      
  slither:
    enabled: true
    priority: 2
    config:
      timeout: 300
      detectors: "all"
      exclude_informational: false
      solc_version: "0.8.19"
      compilation_timeout: 120
      detectors_config:
        - "reentrancy-eth"
        - "reentrancy-no-eth"
        - "unchecked-transfer"
        - "tx-origin"
        - "timestamp"
        - "low-level-calls"
        
  mythril:
    enabled: true
    priority: 3
    config:
      execution_timeout: 600
      max_depth: 50
      strategy: "dfs"
      loop_bound: 3
      modules:
        - "ether_thief"
        - "external_calls"
        - "integer"
        - "assertion_failure"
        - "tx_order_dep"
        - "unchecked_return_value"
        
  manticore:
    enabled: true
    priority: 4
    config:
      timeout: 1200
      max_states: 100
      procs: 4
      verbosity: 2
      detectors: "all"
      workspace_size_limit: "10GB"

# Database Configuration
database:
  host: "scanner-postgres"
  port: 5432
  name: "ultimate_scanner"
  user: "scanner_user"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  
  # Tables
  tables:
    scan_jobs: "scan_jobs"
    scan_results: "scan_results"
    vulnerability_reports: "vulnerability_reports"
    quantum_detections: "quantum_detections"
    compliance_audits: "compliance_audits"

# Redis Configuration
redis:
  host: "scanner-redis"
  port: 6379
  databases:
    cache: 0
    quantum_scanner: 1
    slither_scanner: 2
    mythril_scanner: 3
    manticore_scanner: 4
    orchestrator: 5
    
  # Cache settings
  cache:
    default_ttl: 3600
    scan_result_ttl: 86400
    max_memory: "1gb"
    eviction_policy: "allkeys-lru"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3005"
    - "http://localhost:82"
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
    
  # Authentication
  auth:
    jwt_secret_key: "${JWT_SECRET_KEY}"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7

# WebSocket Configuration
websocket:
  host: "0.0.0.0"
  port: 8765
  max_connections: 1000
  heartbeat_interval: 30
  
  # Real-time features
  real_time:
    scan_progress: true
    vulnerability_alerts: true
    quantum_detections: true
    system_health: true

# Monitoring and Metrics
monitoring:
  prometheus:
    enabled: true
    port: 9090
    metrics_path: "/metrics"
    
  metrics:
    - name: "scans_total"
      type: "counter"
      description: "Total number of scans performed"
    - name: "vulnerabilities_detected_total"
      type: "counter"
      description: "Total vulnerabilities detected"
    - name: "quantum_threats_detected_total"
      type: "counter"
      description: "Total quantum threats detected"
    - name: "scan_duration_seconds"
      type: "histogram"
      description: "Time taken to complete scans"
    - name: "scanner_health_score"
      type: "gauge"
      description: "Overall scanner system health"

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  handlers:
    - "console"
    - "file"
    - "elasticsearch"
    
  files:
    - path: "/app/logs/scanner.log"
      max_size: "100MB"
      backup_count: 5
    - path: "/app/logs/quantum.log"
      max_size: "50MB"
      backup_count: 3
      
  elasticsearch:
    enabled: true
    hosts:
      - "http://quantum-elasticsearch:9200"
    index_pattern: "scanner-logs-{date}"

# Security Configuration
security:
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    
  audit:
    enabled: true
    log_all_actions: true
    immutable_trail: true
    
  compliance:
    frameworks:
      - "SOX"
      - "GDPR"
      - "PCI_DSS"
      - "NIST"
      - "ISO_27001"
    reporting_enabled: true
    auto_compliance_checks: true

# Notification Configuration
notifications:
  channels:
    email:
      enabled: true
      smtp_server: "${SMTP_SERVER}"
      smtp_port: 587
      username: "${SMTP_USERNAME}"
      password: "${SMTP_PASSWORD}"
      
    slack:
      enabled: true
      webhook_url: "${SLACK_WEBHOOK_URL}"
      
    webhook:
      enabled: true
      endpoints:
        - url: "${WEBHOOK_URL}"
          method: "POST"
          headers:
            Authorization: "Bearer ${WEBHOOK_TOKEN}"
            
  alert_rules:
    critical_vulnerability:
      severity: "critical"
      channels: ["email", "slack", "webhook"]
      immediate: true
      
    quantum_threat:
      severity: "high"
      channels: ["email", "slack", "webhook"]
      immediate: true
      
    scan_failure:
      severity: "medium"
      channels: ["email"]
      immediate: false

# Integration with Quantum Mempool Monitor
quantum_integration:
  enabled: true
  quantum_monitor_url: "http://quantum-monitor:8000"
  mempool_service_url: "http://quantum-monitor:8002"
  sync_interval: 60
  
  # Data sharing
  share_quantum_detections: true
  share_vulnerability_reports: true
  share_compliance_data: true
  
  # Real-time synchronization
  real_time_sync:
    enabled: true
    websocket_url: "ws://quantum-monitor:8082/ws"
    topics:
      - "quantum_alerts"
      - "vulnerability_reports"
      - "compliance_events"

# Performance Tuning
performance:
  max_workers: 8
  queue_size: 1000
  batch_size: 50
  
  # Resource limits
  memory_limit: "8GB"
  cpu_limit: "4.0"
  disk_space_limit: "100GB"
  
  # Optimization
  cache_enabled: true
  parallel_scanning: true
  result_compression: true
