!function(){var t=!0,v=null,F=!1;
(function(){function da(e){function l(){try{P.doScroll("left")}catch(e){V(l,50);return}B("poll")}function B(l){if(!("readystatechange"==l.type&&"complete"!=x.readyState)&&(("load"==l.type?p:x)[E](r+l.type,B,F),!n&&(n=t)))e.call(p,l.type||l)}var ba=x.addEventListener,n=F,I=t,z=ba?"addEventListener":"attachEvent",E=ba?"removeEventListener":"detachEvent",r=ba?"":"on";if("complete"==x.readyState)e.call(p,"lazy");else{if(x.createEventObject&&P.doScroll){try{I=!p.frameElement}catch(G){}I&&l()}x[z](r+"DOMContentLoaded",
B,F);x[z](r+"readystatechange",B,F);p[z](r+"load",B,F)}}function W(){X&&da(function(){var e=Q.length;ea(e?function(){for(var l=0;l<e;++l)(function(e){V(function(){p.exports[Q[e]].apply(p,arguments)},0)})(l)}:void 0)})}for(var p=window,V=p.setTimeout,x=document,P=x.documentElement,R=x.head||x.getElementsByTagName("head")[0]||P,E="",G=x.getElementsByTagName("script"),n=G.length;0<=--n;){var S=G[n],Y=S.src.match(/^[^?#]*\/run_prettify\.js(\?[^#]*)?(?:#.*)?$/);if(Y){E=Y[1]||"";S.parentNode.removeChild(S);
break}}var X=t,J=[],T=[],Q=[];E.replace(/[?&]([^&=]+)=([^&]+)/g,function(e,l,B){B=decodeURIComponent(B);l=decodeURIComponent(l);"autorun"==l?X=!/^[0fn]/i.test(B):"lang"==l?J.push(B):"skin"==l?T.push(B):"callback"==l&&Q.push(B)});n=0;for(E=J.length;n<E;++n)(function(){var e=x.createElement("script");e.onload=e.onerror=e.onreadystatechange=function(){if(e&&(!e.readyState||/loaded|complete/.test(e.readyState)))e.onerror=e.onload=e.onreadystatechange=v,--U,U||V(W,0),e.parentNode&&e.parentNode.removeChild(e),
e=v};e.type="text/javascript";e.src="https://cdn.rawgit.com/google/code-prettify/master/loader/lang-"+encodeURIComponent(J[n])+".js";R.insertBefore(e,R.firstChild)})(J[n]);for(var U=J.length,G=[],n=0,E=T.length;n<E;++n)G.push("https://cdn.rawgit.com/google/code-prettify/master/loader/skins/"+encodeURIComponent(T[n])+".css");G.push("https://cdn.rawgit.com/google/code-prettify/master/loader/prettify.css");(function(e){function l(n){if(n!==B){var p=x.createElement("link");p.rel="stylesheet";p.type="text/css";
n+1<B&&(p.error=p.onerror=function(){l(n+1)});p.href=e[n];R.appendChild(p)}}var B=e.length;l(0)})(G);var ea=function(){window.PR_SHOULD_USE_CONTINUATION=t;var e;(function(){function l(b){function d(f){var c=f.charCodeAt(0);if(92!==c)return c;var a=f.charAt(1);return(c=y[a])?c:"0"<=a&&"7">=a?parseInt(f.substring(1),8):"u"===a||"x"===a?parseInt(f.substring(2),16):f.charCodeAt(1)}function h(f){if(32>f)return(16>f?"\\x0":"\\x")+f.toString(16);f=String.fromCharCode(f);return"\\"===f||"-"===f||"]"===f||
"^"===f?"\\"+f:f}function c(f){var c=f.substring(1,f.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);f=[];var a="^"===c[0],b=["["];a&&b.push("^");for(var a=a?1:0,g=c.length;a<g;++a){var k=c[a];if(/\\[bdsw]/i.test(k))b.push(k);else{var k=d(k),q;a+2<g&&"-"===c[a+1]?(q=d(c[a+2]),a+=2):q=k;f.push([k,q]);65>q||122<k||(65>q||90<k||f.push([Math.max(65,k)|32,Math.min(q,90)|32]),97>q||122<k||f.push([Math.max(97,k)&-33,Math.min(q,122)&-33]))}}f.sort(function(f,
a){return f[0]-a[0]||a[1]-f[1]});c=[];g=[];for(a=0;a<f.length;++a)k=f[a],k[0]<=g[1]+1?g[1]=Math.max(g[1],k[1]):c.push(g=k);for(a=0;a<c.length;++a)k=c[a],b.push(h(k[0])),k[1]>k[0]&&(k[1]+1>k[0]&&b.push("-"),b.push(h(k[1])));b.push("]");return b.join("")}function e(f){for(var a=f.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),b=a.length,d=[],g=0,k=0;g<b;++g){var q=a[g];
"("===q?++k:"\\"===q.charAt(0)&&(q=+q.substring(1))&&(q<=k?d[q]=-1:a[g]=h(q))}for(g=1;g<d.length;++g)-1===d[g]&&(d[g]=++l);for(k=g=0;g<b;++g)q=a[g],"("===q?(++k,d[k]||(a[g]="(?:")):"\\"===q.charAt(0)&&(q=+q.substring(1))&&q<=k&&(a[g]="\\"+d[q]);for(g=0;g<b;++g)"^"===a[g]&&"^"!==a[g+1]&&(a[g]="");if(f.ignoreCase&&K)for(g=0;g<b;++g)q=a[g],f=q.charAt(0),2<=q.length&&"["===f?a[g]=c(q):"\\"!==f&&(a[g]=q.replace(/[a-zA-Z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));
return a.join("")}for(var l=0,K=F,m=F,M=0,a=b.length;M<a;++M){var s=b[M];if(s.ignoreCase)m=t;else if(/[a-z]/i.test(s.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){K=t;m=F;break}}for(var y={b:8,t:9,n:10,v:11,f:12,r:13},u=[],M=0,a=b.length;M<a;++M){s=b[M];if(s.global||s.multiline)throw Error(""+s);u.push("(?:"+e(s)+")")}return RegExp(u.join("|"),m?"gi":"g")}function n(b,d){function h(b){var a=b.nodeType;if(1==a){if(!c.test(b.className)){for(a=b.firstChild;a;a=a.nextSibling)h(a);a=b.nodeName.toLowerCase();
if("br"===a||"li"===a)e[m]="\n",K[m<<1]=l++,K[m++<<1|1]=b}}else if(3==a||4==a)a=b.nodeValue,a.length&&(a=d?a.replace(/\r\n?/g,"\n"):a.replace(/[ \t\r\n]+/g," "),e[m]=a,K[m<<1]=l,l+=a.length,K[m++<<1|1]=b)}var c=/(?:^|\s)nocode(?:\s|$)/,e=[],l=0,K=[],m=0;h(b);return{a:e.join("").replace(/\n$/,""),d:K}}function p(b,d,h,c){d&&(b={a:d,e:b},h(b),c.push.apply(c,b.g))}function x(b){for(var d=void 0,h=b.firstChild;h;h=h.nextSibling)var c=h.nodeType,d=1===c?d?b:h:3===c?W.test(h.nodeValue)?b:d:d;return d===
b?void 0:d}function I(b,d){function h(b){for(var m=b.e,l=[m,"pln"],a=0,s=b.a.match(e)||[],y={},u=0,f=s.length;u<f;++u){var H=s[u],D=y[H],A=void 0,g;if("string"===typeof D)g=F;else{var k=c[H.charAt(0)];if(k)A=H.match(k[1]),D=k[0];else{for(g=0;g<r;++g)if(k=d[g],A=H.match(k[1])){D=k[0];break}A||(D="pln")}if((g=5<=D.length&&"lang-"===D.substring(0,5))&&!(A&&"string"===typeof A[1]))g=F,D="src";g||(y[H]=D)}k=a;a+=H.length;if(g){g=A[1];var q=H.indexOf(g),L=q+g.length;A[2]&&(L=H.length-A[2].length,q=L-g.length);
D=D.substring(5);p(m+k,H.substring(0,q),h,l);p(m+k+q,g,G(D,g),l);p(m+k+L,H.substring(L),h,l)}else l.push(m+k,D)}b.g=l}var c={},e;(function(){for(var h=b.concat(d),m=[],r={},a=0,s=h.length;a<s;++a){var y=h[a],u=y[3];if(u)for(var f=u.length;0<=--f;)c[u.charAt(f)]=y;y=y[1];u=""+y;r.hasOwnProperty(u)||(m.push(y),r[u]=v)}m.push(/[\0-\uffff]/);e=l(m)})();var r=d.length;return h}function z(b){var d=[],h=[];b.tripleQuotedStrings?d.push(["str",/^(?:\'\'\'(?:[^\'\\]|\\[\s\S]|\'{1,2}(?=[^\']))*(?:\'\'\'|$)|\"\"\"(?:[^\"\\]|\\[\s\S]|\"{1,2}(?=[^\"]))*(?:\"\"\"|$)|\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$))/,
v,"'\""]):b.multiLineStrings?d.push(["str",/^(?:\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$)|\`(?:[^\\\`]|\\[\s\S])*(?:\`|$))/,v,"'\"`"]):d.push(["str",/^(?:\'(?:[^\\\'\r\n]|\\.)*(?:\'|$)|\"(?:[^\\\"\r\n]|\\.)*(?:\"|$))/,v,"\"'"]);b.verbatimStrings&&h.push(["str",/^@\"(?:[^\"]|\"\")*(?:\"|$)/,v]);var c=b.hashComments;c&&(b.cStyleComments?(1<c?d.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,v,"#"]):d.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\r\n]*)/,
v,"#"]),h.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,v])):d.push(["com",/^#[^\r\n]*/,v,"#"]));b.cStyleComments&&(h.push(["com",/^\/\/[^\r\n]*/,v]),h.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,v]));if(c=b.regexLiterals){var e=(c=1<c?"":"\n\r")?".":"[\\S\\s]";h.push(["lang-regex",RegExp("^(?:^^\\.?|[+-]|[!=]=?=?|\\#|%=?|&&?=?|\\(|\\*=?|[+\\-]=|->|\\/=?|::?|<<?=?|>>?>?=?|,|;|\\?|@|\\[|~|{|\\^\\^?=?|\\|\\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*("+
("/(?=[^/*"+c+"])(?:[^/\\x5B\\x5C"+c+"]|\\x5C"+e+"|\\x5B(?:[^\\x5C\\x5D"+c+"]|\\x5C"+e+")*(?:\\x5D|$))+/")+")")])}(c=b.types)&&h.push(["typ",c]);c=(""+b.keywords).replace(/^ | $/g,"");c.length&&h.push(["kwd",RegExp("^(?:"+c.replace(/[\s,]+/g,"|")+")\\b"),v]);d.push(["pln",/^\s+/,v," \r\n\t\u00a0"]);c="^.[^\\s\\w.$@'\"`/\\\\]*";b.regexLiterals&&(c+="(?!s*/)");h.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,v],["typ",/^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,v],["pln",/^[a-z_$][a-z_$@0-9]*/i,v],["lit",
/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,v,"0123456789"],["pln",/^\\[\s\S]?/,v],["pun",RegExp(c),v]);return I(d,h)}function E(b,d,h){function c(a){var b=a.nodeType;if(1==b&&!l.test(a.className))if("br"===a.nodeName)e(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)c(a);else if((3==b||4==b)&&h){var d=a.nodeValue,s=d.match(r);s&&(b=d.substring(0,s.index),a.nodeValue=b,(d=d.substring(s.index+s[0].length))&&a.parentNode.insertBefore(m.createTextNode(d),
a.nextSibling),e(a),b||a.parentNode.removeChild(a))}}function e(b){function c(a,b){var d=b?a.cloneNode(F):a,f=a.parentNode;if(f){var f=c(f,1),h=a.nextSibling;f.appendChild(d);for(var e=h;e;e=h)h=e.nextSibling,f.appendChild(e)}return d}for(;!b.nextSibling;)if(b=b.parentNode,!b)return;b=c(b.nextSibling,0);for(var d;(d=b.parentNode)&&1===d.nodeType;)b=d;a.push(b)}for(var l=/(?:^|\s)nocode(?:\s|$)/,r=/\r\n?|\n/,m=b.ownerDocument,n=m.createElement("li");b.firstChild;)n.appendChild(b.firstChild);for(var a=
[n],s=0;s<a.length;++s)c(a[s]);d===(d|0)&&a[0].setAttribute("value",d);var y=m.createElement("ol");y.className="linenums";d=Math.max(0,d-1|0)||0;for(var s=0,u=a.length;s<u;++s)n=a[s],n.className="L"+(s+d)%10,n.firstChild||n.appendChild(m.createTextNode("\u00a0")),y.appendChild(n);b.appendChild(y)}function r(b,d){for(var h=d.length;0<=--h;){var c=d[h];Z.hasOwnProperty(c)?$.console&&console.warn("cannot override language handler %s",c):Z[c]=b}}function G(b,d){if(!b||!Z.hasOwnProperty(b))b=/^\s*</.test(d)?
"default-markup":"default-code";return Z[b]}function J(b){var d=b.h;try{var h=n(b.c,b.i),c=h.a;b.a=c;b.d=h.d;b.e=0;G(d,c)(b);var e=/\bMSIE\s(\d+)/.exec(navigator.userAgent),e=e&&8>=+e[1],d=/\n/g,l=b.a,r=l.length,h=0,m=b.d,p=m.length,c=0,a=b.g,s=a.length,y=0;a[s]=r;var u,f;for(f=u=0;f<s;)a[f]!==a[f+2]?(a[u++]=a[f++],a[u++]=a[f++]):f+=2;s=u;for(f=u=0;f<s;){for(var z=a[f],D=a[f+1],A=f+2;A+2<=s&&a[A+1]===D;)A+=2;a[u++]=z;a[u++]=D;f=A}a.length=u;var g=b.c,k;g&&(k=g.style.display,g.style.display="none");
try{for(;c<p;){var q=m[c+2]||r,L=a[y+2]||r,A=Math.min(q,L),x=m[c+1],aa;if(1!==x.nodeType&&(aa=l.substring(h,A))){e&&(aa=aa.replace(d,"\r"));x.nodeValue=aa;var ca=x.ownerDocument,w=ca.createElement("span");w.className=a[y+1];var E=x.parentNode;E.replaceChild(w,x);w.appendChild(x);h<q&&(m[c+1]=x=ca.createTextNode(l.substring(A,q)),E.insertBefore(x,w.nextSibling))}h=A;h>=q&&(c+=2);h>=L&&(y+=2)}}finally{g&&(g.style.display=k)}}catch(C){$.console&&console.log(C&&C.stack||C)}}var $=window,N=["break,continue,do,else,for,if,return,while"],
O=[[N,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],P=[O,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],
Q=[O,"abstract,assert,boolean,byte,extends,finally,final,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],R=[O,"abstract,as,base,bool,by,byte,checked,decimal,delegate,descending,dynamic,event,finally,fixed,foreach,from,group,implicit,in,interface,internal,into,is,let,lock,null,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var,virtual,where"],O=[O,"debugger,eval,export,function,get,instanceof,null,set,undefined,var,with,Infinity,NaN"],
S=[N,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],T=[N,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],N=[N,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],U=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,
W=/\S/,X=z({keywords:[P,R,Q,O,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",S,T,N],hashComments:t,cStyleComments:t,multiLineStrings:t,regexLiterals:t}),Z={};r(X,["default-code"]);r(I([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",
/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),"default-markup htm html mxml xhtml xml xsl".split(" "));r(I([["pln",/^[\s]+/,v," \t\r\n"],["atv",/^(?:\"[^\"]*\"?|\'[^\']*\'?)/,v,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>\'\"\s]*(?:[^>\'\"\s\/]|\/(?=\s)))/],["pun",
/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*\"([^\"]+)\"/i],["lang-js",/^on\w+\s*=\s*\'([^\']+)\'/i],["lang-js",/^on\w+\s*=\s*([^\"\'>\s]+)/i],["lang-css",/^style\s*=\s*\"([^\"]+)\"/i],["lang-css",/^style\s*=\s*\'([^\']+)\'/i],["lang-css",/^style\s*=\s*([^\"\'>\s]+)/i]]),["in.tag"]);r(I([],[["atv",/^[\s\S]+/]]),["uq.val"]);r(z({keywords:P,hashComments:t,cStyleComments:t,types:U}),"c cc cpp cxx cyc m".split(" "));r(z({keywords:"null,true,false"}),["json"]);r(z({keywords:R,hashComments:t,cStyleComments:t,
verbatimStrings:t,types:U}),["cs"]);r(z({keywords:Q,cStyleComments:t}),["java"]);r(z({keywords:N,hashComments:t,multiLineStrings:t}),["bash","bsh","csh","sh"]);r(z({keywords:S,hashComments:t,multiLineStrings:t,tripleQuotedStrings:t}),["cv","py","python"]);r(z({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:t,multiLineStrings:t,regexLiterals:2}),["perl",
"pl","pm"]);r(z({keywords:T,hashComments:t,multiLineStrings:t,regexLiterals:t}),["rb","ruby"]);r(z({keywords:O,cStyleComments:t,regexLiterals:t}),["javascript","js"]);r(z({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:t,multilineStrings:t,tripleQuotedStrings:t,regexLiterals:t}),["coffee"]);r(I([],[["str",/^[\s\S]+/]]),["regex"]);var Y=$.PR={createSimpleLexer:I,
registerLangHandler:r,sourceDecorator:z,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:function(b,d,e){var c=document.createElement("div");c.innerHTML="<pre>"+b+"</pre>";c=c.firstChild;e&&E(c,e,t);J({h:d,j:e,c:c,i:1});return c.innerHTML},prettyPrint:e=e=function(b,d){function e(){for(var c=$.PR_SHOULD_USE_CONTINUATION?
a.now()+250:Infinity;s<r.length&&a.now()<c;s++){for(var d=r[s],n=k,m=d;m=m.previousSibling;){var p=m.nodeType,w=(7===p||8===p)&&m.nodeValue;if(w?!/^\??prettify\b/.test(w):3!==p||/\S/.test(m.nodeValue))break;if(w){n={};w.replace(/\b(\w+)=([\w:.%+-]+)/g,function(a,b,c){n[b]=c});break}}m=d.className;if((n!==k||f.test(m))&&!z.test(m)){p=F;for(w=d.parentNode;w;w=w.parentNode)if(g.test(w.tagName)&&w.className&&f.test(w.className)){p=t;break}if(!p){d.className+=" prettyprinted";p=n.lang;if(!p){var p=m.match(u),
B;if(!p&&(B=x(d))&&A.test(B.tagName))p=B.className.match(u);p&&(p=p[1])}if(D.test(d.tagName))w=1;else var w=d.currentStyle,C=l.defaultView,w=(w=w?w.whiteSpace:C&&C.getComputedStyle?C.getComputedStyle(d,v).getPropertyValue("white-space"):0)&&"pre"===w.substring(0,3);C=n.linenums;if(!(C="true"===C||+C))C=(C=m.match(/\blinenums\b(?::(\d+))?/))?C[1]&&C[1].length?+C[1]:t:F;C&&E(d,C,w);y={h:p,c:d,j:C,i:w};J(y)}}}s<r.length?V(e,250):"function"===typeof b&&b()}for(var c=d||document.body,l=c.ownerDocument||
document,c=[c.getElementsByTagName("pre"),c.getElementsByTagName("code"),c.getElementsByTagName("xmp")],r=[],n=0;n<c.length;++n)for(var m=0,p=c[n].length;m<p;++m)r.push(c[n][m]);var c=v,a=Date;a.now||(a={now:function(){return+new Date}});var s=0,y,u=/\blang(?:uage)?-([\w.]+)(?!\S)/,f=/\bprettyprint\b/,z=/\bprettyprinted\b/,D=/pre|xmp/i,A=/^code$/i,g=/^(?:pre|code|xmp)$/i,k={};e()}};"function"===typeof define&&define.amd&&define("google-code-prettify",[],function(){return Y})})();return e}();U||V(W,
0)})();}()
